### ISSUE TITLE
BATCH_MUL in Chapter09/03_parallel

### ISSUE THREAD

**Issue by sevenfx** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#9]
Hello, really enjoying this second edition!  I'm curious what this `BATCH_MUL` variable is for here.
https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/blob/4915540ca592a5a6d88f8cb63eff2c2ebf57bb06/Chapter09/03_parallel.py#L21
I see that you're sampling a larger batch, adjusting the epsilon tracker with it:
```
epsilon_tracker.frame(frame_idx/BATCH_MUL)
```
And setting the size of the Queue:
```
exp_queue = mp.Queue(maxsize=BATCH_MUL*2)
```
The FPS appeared low in my Tensorboard logs and, so I am not sure if this is what you intended.  While I am seeing a speedup, I'm not seeing one quite as drastically as you are.  It appears that there is still only a single env generating experience, but BATCH_MUL would make more sense to me if there were more than one.  I'm planning to dig in deeper but just wanted to hear your thoughts on that.  Thanks!

**Comment by Shmuma** [comment]
Hi!

That's a really good question. This parameter wasn't explained in the book and, honestly, I don't remember exact meaning of this parameter. Looks like it was added during my experiments on my hardware during tuning of the example, so, you might need to tweak it to get better results. From the logic I can make the following suggestions:

This parameter multiplies the batch we're using during the training to compensate faster samples inflow from "play process". In `BatchGenerator.__iter__` method, we fetch all the samples available in the queue (produced by the play process) and then yield the training batch. Probably I've noticed that play process is able to produce more than one fresh observation, and to compensate this, batch size need to be increased and epsilon decay should be decreased accordingly.

But your performance might differ due to different GPU and platform (I used GTX 1080Ti and core i7), so, this batch multiplier to get optimal performance. 

In any case, I encourage you to experiment with the code to get better understanding what's going on. I'd start with monitoring of communication between play and train processes (amount of samples, train delays, etc).
